version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Build 2.0-sdk
          command: |
            DOTNET_SDK_VERSION=2.0-sdk
            docker build --build-arg DOTNET_SDK_VERSION=$DOTNET_SDK_VERSION -t $DOCKER_USER/dotnet-mono:$DOTNET_SDK_VERSION .
      - run:
          name: Push to DockerHub
          command: |
            DOTNET_SDK_VERSION=2.0-sdk
            docker push $DOCKER_USER/dotnet-mono:$DOTNET_SDK_VERSION
